### PR TITLE
ft-#160365951 User should be able to view their profile.

### PR DESCRIPTION
**Pull request by KelynPNjeri**
**What the PR contains:**
The PR contains the UI design of the Profile page to the StackOverflow-lite website. It allows users to view the questions they have posted and the questions to which they have given answers. This page also allows users to complete their profile as a user in which they are able to enter their full name, their tagline and also tell us a little bit about themselves.

**PT stories completed:**
ft-[#160365951](https://www.pivotaltracker.com/story/show/160365951)

### CODE REVIEW

**Comment by Gidraf** [comment]
please include screen short of the output, for effective review

**Comment by Gidraf** [comment]
I like the way you have tried to arrange your data but I suggest perhaps the personal details and the ```tell me more``` part should be in the left-nav so that the questions and answers remain inside the central nav... hence 
1. the user won't scroll that much just to find the details he/she wants i.e. editing his profile info
2. it will reduce a lot of work to be done on back end since the front end will guide on data structures and return value 
in color picking and theme  I should suggest you look at https://material.io/design/color/the-color-system.html#color-theme-creation will greatly guide you

**Comment by KelynPNjeri** [comment]
Thank you for that. Perhaps I can apply that on my next web app.

**Comment by Eyansky** [comment]
1. Use these guidelines for your pr
https://github.com/andela/bestpractices/wiki/Git-naming-conventions-and-best-practices

**Pull request merged**
